AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  myawssamplanet

  Sample SAM Template for myawssamplanet

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  MyAwsSamFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: MyAwsSamFunction
      Handler: com.mydeveloperplanet.myawslambdajavaplanet.LambdaJava::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        MyAwsLambdaJavaGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /myawslambdajava
            Method: get
        MyAwsLambdaJavaPost:
          Type: Api
          Properties:
            Path: /myawslambdajava
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MyAwsSamApi:
    Description: "API Gateway endpoint URL for Prod stage for LambdaJava function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/myawslambdajava/"
  MyAwsSamFunction:
    Description: "LambdaJava Lambda Function ARN"
    Value: !GetAtt MyAwsSamFunction.Arn
  MyAwsSamFunctionIamRole:
    Description: "Implicit IAM Role created for LambdaJava function"
    Value: !GetAtt MyAwsSamFunctionRole.Arn
